name: Build and Publish macOS Application

# on:
#   workflow_dispatch:
on:
  push:
    branches:
      - main
      - githubActions

jobs:
  build-and-publish:
    runs-on: macOS-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Build project
      run: |
        xcodebuild \
          -project ProjectCodeAssistant.xcodeproj \
          -scheme ProjectCodeAssistant \
          -configuration Release \
          -destination generic/platform=macOS \
          build

    - name: Release
      uses: softprops/action-gh-release@v1

    - name: Publish release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ProjectCodeAssistant.app
        asset_name: ProjectCodeAssistant.app
        asset_content_type: application/octet-stream
